### ISSUE TITLE
File create/rename loses focus

### ISSUE THREAD

**Issue by bbros-dev** [Gruntfuggly/activitusbar#44] opened 2021-05-11 08:39 UTC
When attempting to create or edit a file/folder the text area to (re)name loses focus and the task cannot be completed.

VSCode extension bisect identified this extension as the source of the behavior:

A/B Experiment Info:

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30299255
```

system Info:

```


CPUs | Intel(R) Celeron(R) CPU G550T @ 2.20GHz (2 x 2195)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: disabled_off oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 5, 7, 6
Memory (System) | 15.51GB (3.48GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id 297ecd66-bd98-4ad0-b7be-4fdb48d7f2b5
Screen Reader | no
VM | 0%


```

**Comment by Gruntfuggly** [comment] 2021-05-11 22:55
Please could you describe how to reproduce the problem? If I use add file or add folder it works fine.

Please list the steps, i.e what buttons you are pressing and what happens at each stage.

**Comment by bbros-dev** [comment] 2021-05-12 03:06
Selecting/pressing the "New file" or "New folder" icon in the file explorer pane should trigger it.
Fitting F2 on a file should also trigger it.

To reproduce:
I've noticed that the issue isn't triggered in an empty workspace.
So, I believe at least the Go and Rust extensions should be 'actively in use' i.e. enabled is not enough - maybe others too.

Is there are way to query which extensions are actively in use when you open a project? 

VSCode bisect always shows this extension as the source of the behavior.

**Comment by bbros-dev** [comment] 2021-05-12 04:30
OK I can trigger and stop this at this at will via the Rust analyzer plugin.

Specifically, omit `.git` from the "Files: Watcher Exclude" list

The Dev console for VSCode should be spammed by the following types of messages:

```
[Extension Host] Event[file] 2 - /home/hedge/src/networkmesh.io/.git/modules/web/docs/themes/docsy/index.lock
workbench.desktop.main.js:62 [Extension Host] Event[file] 0 - /home/hedge/src/networkmesh.io/.git/index.lock
workbench.desktop.main.js:62 [Extension Host] Event[file] 0 - /home/hedge/src/networkmesh.io/.git/modules/web/docs/themes/docsy/index.lock
workbench.desktop.main.js:62 [Extension Host] Event[file] 2 - /home/hedge/src/networkmesh.io/.git/index.lock
workbench.desktop.main.js:62 
```

Try to create new file/folder or rename a file and you should loose focus before you are able to complete the task.

Now add this setting:

```
"files.watcherExclude": {
  "**/.git/**": true,
}
```

The dev console should no longer be spammed, and new file/new folder/rename activities can complete.

It would appear this extension interacts with some file events to expose this behavior?

**Comment by bbros-dev** [comment] 2021-05-12 04:41
> The extension adds buttons to the status bar - I don't see how it can interact with the file name field.

This had me puzzled to, but it is likely related to the file events - identified above - since the git "button" that activitus adds shows the counts of edited files, and this is updated in the background without user input (i.e. I don't have to hit refresh/F5 to see the count of changes)?  

Of course I'm just guessing at this stage.

**Comment by bbros-dev** [comment] 2021-05-12 04:45
I wonder if this was trigger by issue #43?

**Comment by Gruntfuggly** [comment] 2021-05-12 07:56
I expect you've already tried, but does it still happen when `activitusbar.showSourceControlCounter` is set to false?

Also, could you try installing the previous version of the extension and check if it still happens?

**Comment by bbros-dev** [comment] 2021-05-13 00:52
Okay:

1. Remove `**.git**` form file watcher exclude list
2. Console is spammed with file events
3. new file/folder and rename lose focus
4. Set `activitusbar.showSourceControlCounter` to false
5. Console stops being spammed with file events
6. new file/folder and rename work as expected

So it seems the implementation of #43 is the source of this behavior?

**Comment by Gruntfuggly** [comment] 2021-05-13 10:24
Thanks for you work investigating it. This version introduced the monitoring to update the counter, so the older version should work as expected. 

The only thing that happens when the count is processed is that the status bar item is changed, which shouldn't have any effect on focus.

This extension shouldn't be logging anything when its file watcher detects changes. Can you see what is generating the messages to the console? Could you post a screenshot of the console messages?

I'm guessing that another extension is being triggered by the output maybe.

**Comment by bbros-dev** [comment] 2021-05-13 21:54
The defining characteristic appears to be a flood of the `.git/index.lock` file events.  

All cases where file/folder new and (re)name work show a small number of these events.  The project where it does not work shows a flood of these events.

Unfortunately commercial restrictions mean I can't post anything related to the project where this occurs.  
The closest I can find in my OSS repo's is the zero2production repository, the adversely affected project shows a console similar to the following with an order of magnitude more occurrences of `.git/index.lock`:

![image](https://user-images.githubusercontent.com/60454087/118191970-c3e44100-b488-11eb-884f-0163935dda6c.png)

**Comment by bbros-dev** [comment] 2021-05-13 22:01
Apart from turning `activitusbar.showSourceControlCounter` on/off is there anything I can do to trigger more of these `.git/index.lock` events?

**Comment by Gruntfuggly** [comment] 2021-05-13 22:13
When `activitusbar.showSourceControlCounter` is enabled, it creates file watcher. Any file change event triggers an update (after a delay so multiple events only trigger one update). 

Nothing in that log looks like it's associated with the extension, so I honestly don't know why the focus is being affected.

**Comment by bbros-dev** [comment] 2021-05-13 22:21
Thanks, I've added some additional data from the affected IDE instance.

**Comment by bbros-dev** [comment] 2021-05-13 22:33
As someone ignorant of the VSCode internals.... 

it does make sense to me that the counter update interferes with user input - I want to input some text so the IDE displays this next to a file icon, the extension wants to input some text to display next to the git repo icon.

With the flood of file events it appears the extension counter update is able to circumvent the mechanism used give the user input exclusive access.

Of course that is a high level ignorant interpretation.

Is there another mechanism/api you can use to input/update the counter value?

Anyway, I'm happy to disable the counter to get my input back.

**Comment by Gruntfuggly** [comment] 2021-05-13 22:56
The extension only updates the status bar items - which shouldn't interfere with any user input. There's no need for any user interaction with the extension at all, it all happens in the background.

I'm really not sure why you're seeing what you're seeing. 

Sounds like disabling the counter is the only option.

**Comment by bbros-dev** [comment] 2021-05-16 02:30
I have now observed this behavior in another project, and confirm setting `activitusbar.showSourceControlCounter` to false worksaround the problem.

This project has no Rust in it - so we can eliminate my earlier conjecture the rust analyzer or language server was involved.

One thing both projects have in common is an instance of Hashicorp Vault storing its raft DB in the repository.  Each project has its own Vault for bootstrapping secrets.
These are serverless, single user/purpose setups of Vault, but they are known to touch/alter the storage artifacts - they show up as changes in the Git status window.

**Comment by hoodedice** [comment] 2021-05-24 20:52
I have this issue as well, in multiple projects. Disabling `showSourceControlCounter` does fix the problem. Please tell me what I can do to help resolve this issue.

**Comment by Gruntfuggly** [comment] 2021-05-28 09:49
I think I'll disable it by default. I don't understand why it has the effect that it does. If anybody could capture a video showing what happens I'd very much appreciate it.

**Comment by tsekka** [comment] 2021-05-28 11:42
There's a screen recording:
https://user-images.githubusercontent.com/43533692/119978802-be2b4700-bfc2-11eb-93b7-a71593c749b5.mp4

**Comment by tsekka** [comment] 2021-05-28 11:56
I don't understand if it could be OS related, but anyway I can easily reproduce the issue on 2 separate ubuntu machines (one having ubuntu 20.04, another 21.04) by simply cloning some php project, eg: `git clone https://github.com/laravel/framework.git `

**Comment by Gruntfuggly** [comment] 2021-05-28 13:54
Thanks for the video. It doesn't happen for me on OSX or Ubuntu 18.04. Maybe it's a bug in VSCode, as it makes no sense to me.

If you have time, you could try commenting out line of 436 (`setScmCount( total );`) of
```
.vscode/extensions/gruntfugggly.activitusbar.0.0.46/extension.js
```
That would then isolate if the problem is to do with the file watcher, or updating the button.

I think it's probably the file watcher - I'm guessing there is some event being fired due to the rename.

**Comment by tsekka** [comment] 2021-05-29 06:16
Hi, commenting line 436 (setScmCount( total );) did not fix it.

**Comment by bbros-dev** [comment] 2021-05-29 08:23
> Maybe it's a bug in VSCode, as it makes no sense to me.

It could be a VSCode bug that this extension is triggering.
Before I isolated as the extension that triggered this bahavior I do remeber seeing an (old) VSCode issue report around user input losing focus.  However that bug was fixed.

Can't recall the bug ... will update if I manage to find it again.

**Comment by bbros-dev** [comment] 2021-05-29 08:31
Some issues that may provide a clue:

- https://github.com/microsoft/vscode/issues/115500 (good luck working out the duplicate and commit that fixed the issue)
- https://github.com/microsoft/vscode/issues/102498

**Comment by Gruntfuggly** [comment] 2021-06-03 14:05
@tsekka thanks for trying that - confirms what I thought. 

To be honest, I don't think there is anything I can do to fix this. Now that the counter is disabled by default, it shouldn't affect anybody unexpectedly, so I'm going to close this.

If anybody has any ideas of where to even start trying to find the issue, please feel free to reopen.

**Closed by Gruntfuggly** 2021-06-03 14:05 UTC

**Comment by bbros-dev** [comment] 2021-06-03 14:51
I'd only suggest escalating upstream - its definitely a bug - reproducible and affecting several users.  As best you can you've determined its nothing in your code.... so it must be in upstream code?  

They will also likely know enough to either own it and fix or point you in the right direction.

This might be prematurely closed because we haven't yet isolated what is the common attribute among us.
We can all reproduce it in an affected repository, but not not all repositories we each have seem to trigger the behavior.

@tsekka in those PHP repositories do have running in the background or foreground some type of dev web-server that refreshes pages on changes? 
Anything else that might be monitoring or changing files.  In my case the common attribute is a Vault server with its raft files in the repository.  git shows me these files have changed content even when I do nothing - likely somthing in the raft protocol.

**Comment by tsekka** [comment] 2021-06-04 13:29
@bbros-dev  I tried disabling all background processes that I can think of and did not find it and still it persists.

@Gruntfuggly no problem. Personally I don't care much about source control counter in activity bar so disabling it is good enough fix for me...
